# -*- coding: utf-8 -*-
"""student_per_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dKwtpEOYfYDkZ-gvdGb7Gx8I9Z6XWOK
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/student-por.csv")
df.shape
print("no of students are",df.shape[0])
print("no of null values are:",df.isna().sum())
print(df["studytime"].mean())
print(df.info())
print(df.duplicated().sum())
print("average age",df["age"].mean())
print("average grade",df["G3"].mean())
print("max grade",df["G3"].max())
print("min grade",df["G3"].min())
print(df["sex"].value_counts())
print(df["internet"].value_counts(normalize="true")*100)
percentage=(df["internet"]=="yes").mean()*100
print("perc of students having internet",percentage)
print(df.groupby("studytime")["G3"].mean())
print(df["absences"].corr(df["G3"]))
print(df["G2"].corr(df["G3"]))
correlations = df.corr(numeric_only=True)["G3"].drop("G3")

print(correlations.abs().sort_values(ascending=False))

#data visualization
import matplotlib.pyplot as plt
df.boxplot(column="G3",by="studytime")
plt.xlabel("G3")
plt.ylabel("studytime")
plt.title("studytime vs final grade")
plt.suptitle("")
plt.show()

#visualizing relation between absences and final grade
df.boxplot(column="G3",by="absences")
plt.xlabel("G3")
plt.ylabel("absences")
plt.title("absences vs final grade")
plt.suptitle("")
plt.show()
#

plt.scatter(df["G2"], df["G3"])
plt.xlabel("G2")
plt.ylabel("G3")
plt.title("G2 vs G3")
plt.show()

#bar chart for the average sex and grade
avgg3=df.groupby("sex")["G3"].mean()
avgg3.plot(kind="bar")
plt.title("AVG GRADE AND GENDER ")
plt.xlabel("gender")
plt.ylabel("average grade")
plt.xticks(rotation=0)
plt.show()

#MACHINE LEARNING
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
X = df[["studytime", "failures", "absences", "G1", "G2"]]
y = df["G3"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("mean squared error:",mse)
print("r2 score:",r2)
print(y_pred)
comparison=pd.DataFrame({"actual_G3":y_test,"predicted_G3":y_pred})
print(comparison)
comparison["difference"]=comparison["actual_G3"]-comparison["predicted_G3"]
print(comparison)

from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X = df[["studytime", "failures", "absences"]]
y=df["G3"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print(y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print("mean squared error:",mse)
print("r2 score:",r2)
print("mae score",mae)

